### ISSUE TITLE
Support ES2018 Unicode property escapes

### ISSUE THREAD

**Issue by mathiasbynens** [shapesecurity/shift-regexp-acceptor-js#2]
The grammar itself is pretty straightforward.

To verify the supported list of properties (and their aliases) and values (and their aliases), you could use the following packages:

- https://github.com/mathiasbynens/unicode-match-property-ecmascript
- https://github.com/mathiasbynens/unicode-match-property-value-ecmascript

I keep these packages in sync with the upstream spec, updating them [whenever Unicode releases a new version](https://github.com/tc39/ecma262/issues/1219).

**Comment by michaelficarra** [comment]
Fixed by #7.
